// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: card.proto

package etc_meisaiv1

import (
	_ "github.com/yhonda-ohishi/db-handler-server/google/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardStatus int32

const (
	CardStatus_CARD_STATUS_UNSPECIFIED CardStatus = 0
	CardStatus_CARD_STATUS_ACTIVE      CardStatus = 1
	CardStatus_CARD_STATUS_SUSPENDED   CardStatus = 2
	CardStatus_CARD_STATUS_EXPIRED     CardStatus = 3
)

// Enum value maps for CardStatus.
var (
	CardStatus_name = map[int32]string{
		0: "CARD_STATUS_UNSPECIFIED",
		1: "CARD_STATUS_ACTIVE",
		2: "CARD_STATUS_SUSPENDED",
		3: "CARD_STATUS_EXPIRED",
	}
	CardStatus_value = map[string]int32{
		"CARD_STATUS_UNSPECIFIED": 0,
		"CARD_STATUS_ACTIVE":      1,
		"CARD_STATUS_SUSPENDED":   2,
		"CARD_STATUS_EXPIRED":     3,
	}
)

func (x CardStatus) Enum() *CardStatus {
	p := new(CardStatus)
	*p = x
	return p
}

func (x CardStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_card_proto_enumTypes[0].Descriptor()
}

func (CardStatus) Type() protoreflect.EnumType {
	return &file_card_proto_enumTypes[0]
}

func (x CardStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardStatus.Descriptor instead.
func (CardStatus) EnumDescriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{0}
}

type VehicleType int32

const (
	VehicleType_VEHICLE_TYPE_UNSPECIFIED VehicleType = 0
	VehicleType_VEHICLE_TYPE_REGULAR     VehicleType = 1
	VehicleType_VEHICLE_TYPE_KEI         VehicleType = 2
	VehicleType_VEHICLE_TYPE_LARGE       VehicleType = 3
)

// Enum value maps for VehicleType.
var (
	VehicleType_name = map[int32]string{
		0: "VEHICLE_TYPE_UNSPECIFIED",
		1: "VEHICLE_TYPE_REGULAR",
		2: "VEHICLE_TYPE_KEI",
		3: "VEHICLE_TYPE_LARGE",
	}
	VehicleType_value = map[string]int32{
		"VEHICLE_TYPE_UNSPECIFIED": 0,
		"VEHICLE_TYPE_REGULAR":     1,
		"VEHICLE_TYPE_KEI":         2,
		"VEHICLE_TYPE_LARGE":       3,
	}
)

func (x VehicleType) Enum() *VehicleType {
	p := new(VehicleType)
	*p = x
	return p
}

func (x VehicleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleType) Descriptor() protoreflect.EnumDescriptor {
	return file_card_proto_enumTypes[1].Descriptor()
}

func (VehicleType) Type() protoreflect.EnumType {
	return &file_card_proto_enumTypes[1]
}

func (x VehicleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleType.Descriptor instead.
func (VehicleType) EnumDescriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{1}
}

// ETCCard represents an electronic toll collection card
type ETCCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	ExpiryDate    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	Status        CardStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=etc_meisai.v1.CardStatus" json:"status,omitempty"`
	VehicleNumber string                 `protobuf:"bytes,6,opt,name=vehicle_number,json=vehicleNumber,proto3" json:"vehicle_number,omitempty"`
	VehicleType   VehicleType            `protobuf:"varint,7,opt,name=vehicle_type,json=vehicleType,proto3,enum=etc_meisai.v1.VehicleType" json:"vehicle_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ActivatedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=activated_at,json=activatedAt,proto3" json:"activated_at,omitempty"`
	DeactivatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deactivated_at,json=deactivatedAt,proto3" json:"deactivated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ETCCard) Reset() {
	*x = ETCCard{}
	mi := &file_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETCCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETCCard) ProtoMessage() {}

func (x *ETCCard) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETCCard.ProtoReflect.Descriptor instead.
func (*ETCCard) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{0}
}

func (x *ETCCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ETCCard) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ETCCard) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *ETCCard) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *ETCCard) GetStatus() CardStatus {
	if x != nil {
		return x.Status
	}
	return CardStatus_CARD_STATUS_UNSPECIFIED
}

func (x *ETCCard) GetVehicleNumber() string {
	if x != nil {
		return x.VehicleNumber
	}
	return ""
}

func (x *ETCCard) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_VEHICLE_TYPE_UNSPECIFIED
}

func (x *ETCCard) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ETCCard) GetActivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActivatedAt
	}
	return nil
}

func (x *ETCCard) GetDeactivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeactivatedAt
	}
	return nil
}

// Request messages
type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{1}
}

func (x *GetCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardNumber    string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	ExpiryDate    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	VehicleNumber string                 `protobuf:"bytes,4,opt,name=vehicle_number,json=vehicleNumber,proto3" json:"vehicle_number,omitempty"`
	VehicleType   VehicleType            `protobuf:"varint,5,opt,name=vehicle_type,json=vehicleType,proto3,enum=etc_meisai.v1.VehicleType" json:"vehicle_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateCardRequest) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *CreateCardRequest) GetVehicleNumber() string {
	if x != nil {
		return x.VehicleNumber
	}
	return ""
}

func (x *CreateCardRequest) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_VEHICLE_TYPE_UNSPECIFIED
}

type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleNumber string                 `protobuf:"bytes,2,opt,name=vehicle_number,json=vehicleNumber,proto3" json:"vehicle_number,omitempty"`
	VehicleType   VehicleType            `protobuf:"varint,3,opt,name=vehicle_type,json=vehicleType,proto3,enum=etc_meisai.v1.VehicleType" json:"vehicle_type,omitempty"`
	Status        CardStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=etc_meisai.v1.CardStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCardRequest) GetVehicleNumber() string {
	if x != nil {
		return x.VehicleNumber
	}
	return ""
}

func (x *UpdateCardRequest) GetVehicleType() VehicleType {
	if x != nil {
		return x.VehicleType
	}
	return VehicleType_VEHICLE_TYPE_UNSPECIFIED
}

func (x *UpdateCardRequest) GetStatus() CardStatus {
	if x != nil {
		return x.Status
	}
	return CardStatus_CARD_STATUS_UNSPECIFIED
}

type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsRequest) Reset() {
	*x = ListCardsRequest{}
	mi := &file_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsRequest) ProtoMessage() {}

func (x *ListCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsRequest.ProtoReflect.Descriptor instead.
func (*ListCardsRequest) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{5}
}

func (x *ListCardsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListCardsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCardsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*ETCCard             `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsResponse) Reset() {
	*x = ListCardsResponse{}
	mi := &file_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsResponse) ProtoMessage() {}

func (x *ListCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsResponse.ProtoReflect.Descriptor instead.
func (*ListCardsResponse) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{6}
}

func (x *ListCardsResponse) GetCards() []*ETCCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *ListCardsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_card_proto protoreflect.FileDescriptor

const file_card_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"card.proto\x12\retc_meisai.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xe6\x03\n" +
	"\aETCCard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12;\n" +
	"\vexpiry_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.etc_meisai.v1.CardStatusR\x06status\x12%\n" +
	"\x0evehicle_number\x18\x06 \x01(\tR\rvehicleNumber\x12=\n" +
	"\fvehicle_type\x18\a \x01(\x0e2\x1a.etc_meisai.v1.VehicleTypeR\vvehicleType\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\factivated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vactivatedAt\x12A\n" +
	"\x0edeactivated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rdeactivatedAt\" \n" +
	"\x0eGetCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf0\x01\n" +
	"\x11CreateCardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12;\n" +
	"\vexpiry_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\x12%\n" +
	"\x0evehicle_number\x18\x04 \x01(\tR\rvehicleNumber\x12=\n" +
	"\fvehicle_type\x18\x05 \x01(\x0e2\x1a.etc_meisai.v1.VehicleTypeR\vvehicleType\"\xbc\x01\n" +
	"\x11UpdateCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0evehicle_number\x18\x02 \x01(\tR\rvehicleNumber\x12=\n" +
	"\fvehicle_type\x18\x03 \x01(\x0e2\x1a.etc_meisai.v1.VehicleTypeR\vvehicleType\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.etc_meisai.v1.CardStatusR\x06status\"#\n" +
	"\x11DeleteCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x10ListCardsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"i\n" +
	"\x11ListCardsResponse\x12,\n" +
	"\x05cards\x18\x01 \x03(\v2\x16.etc_meisai.v1.ETCCardR\x05cards\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*u\n" +
	"\n" +
	"CardStatus\x12\x1b\n" +
	"\x17CARD_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CARD_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15CARD_STATUS_SUSPENDED\x10\x02\x12\x17\n" +
	"\x13CARD_STATUS_EXPIRED\x10\x03*s\n" +
	"\vVehicleType\x12\x1c\n" +
	"\x18VEHICLE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14VEHICLE_TYPE_REGULAR\x10\x01\x12\x14\n" +
	"\x10VEHICLE_TYPE_KEI\x10\x02\x12\x16\n" +
	"\x12VEHICLE_TYPE_LARGE\x10\x032\xff\x03\n" +
	"\vCardService\x12\\\n" +
	"\aGetCard\x12\x1d.etc_meisai.v1.GetCardRequest\x1a\x16.etc_meisai.v1.ETCCard\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/cards/{id}\x12`\n" +
	"\n" +
	"CreateCard\x12 .etc_meisai.v1.CreateCardRequest\x1a\x16.etc_meisai.v1.ETCCard\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/cards\x12e\n" +
	"\n" +
	"UpdateCard\x12 .etc_meisai.v1.UpdateCardRequest\x1a\x16.etc_meisai.v1.ETCCard\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/cards/{id}\x12b\n" +
	"\n" +
	"DeleteCard\x12 .etc_meisai.v1.DeleteCardRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/cards/{id}\x12e\n" +
	"\tListCards\x12\x1f.etc_meisai.v1.ListCardsRequest\x1a .etc_meisai.v1.ListCardsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/cardsB\xa8\x01\n" +
	"\x11com.etc_meisai.v1B\tCardProtoP\x01Z7github.com/yhonda-ohishi/db-handler-server;etc_meisaiv1\xa2\x02\x03EXX\xaa\x02\fEtcMeisai.V1\xca\x02\fEtcMeisai\\V1\xe2\x02\x18EtcMeisai\\V1\\GPBMetadata\xea\x02\rEtcMeisai::V1b\x06proto3"

var (
	file_card_proto_rawDescOnce sync.Once
	file_card_proto_rawDescData []byte
)

func file_card_proto_rawDescGZIP() []byte {
	file_card_proto_rawDescOnce.Do(func() {
		file_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_card_proto_rawDesc), len(file_card_proto_rawDesc)))
	})
	return file_card_proto_rawDescData
}

var file_card_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_card_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_card_proto_goTypes = []any{
	(CardStatus)(0),               // 0: etc_meisai.v1.CardStatus
	(VehicleType)(0),              // 1: etc_meisai.v1.VehicleType
	(*ETCCard)(nil),               // 2: etc_meisai.v1.ETCCard
	(*GetCardRequest)(nil),        // 3: etc_meisai.v1.GetCardRequest
	(*CreateCardRequest)(nil),     // 4: etc_meisai.v1.CreateCardRequest
	(*UpdateCardRequest)(nil),     // 5: etc_meisai.v1.UpdateCardRequest
	(*DeleteCardRequest)(nil),     // 6: etc_meisai.v1.DeleteCardRequest
	(*ListCardsRequest)(nil),      // 7: etc_meisai.v1.ListCardsRequest
	(*ListCardsResponse)(nil),     // 8: etc_meisai.v1.ListCardsResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_card_proto_depIdxs = []int32{
	9,  // 0: etc_meisai.v1.ETCCard.expiry_date:type_name -> google.protobuf.Timestamp
	0,  // 1: etc_meisai.v1.ETCCard.status:type_name -> etc_meisai.v1.CardStatus
	1,  // 2: etc_meisai.v1.ETCCard.vehicle_type:type_name -> etc_meisai.v1.VehicleType
	9,  // 3: etc_meisai.v1.ETCCard.created_at:type_name -> google.protobuf.Timestamp
	9,  // 4: etc_meisai.v1.ETCCard.activated_at:type_name -> google.protobuf.Timestamp
	9,  // 5: etc_meisai.v1.ETCCard.deactivated_at:type_name -> google.protobuf.Timestamp
	9,  // 6: etc_meisai.v1.CreateCardRequest.expiry_date:type_name -> google.protobuf.Timestamp
	1,  // 7: etc_meisai.v1.CreateCardRequest.vehicle_type:type_name -> etc_meisai.v1.VehicleType
	1,  // 8: etc_meisai.v1.UpdateCardRequest.vehicle_type:type_name -> etc_meisai.v1.VehicleType
	0,  // 9: etc_meisai.v1.UpdateCardRequest.status:type_name -> etc_meisai.v1.CardStatus
	2,  // 10: etc_meisai.v1.ListCardsResponse.cards:type_name -> etc_meisai.v1.ETCCard
	3,  // 11: etc_meisai.v1.CardService.GetCard:input_type -> etc_meisai.v1.GetCardRequest
	4,  // 12: etc_meisai.v1.CardService.CreateCard:input_type -> etc_meisai.v1.CreateCardRequest
	5,  // 13: etc_meisai.v1.CardService.UpdateCard:input_type -> etc_meisai.v1.UpdateCardRequest
	6,  // 14: etc_meisai.v1.CardService.DeleteCard:input_type -> etc_meisai.v1.DeleteCardRequest
	7,  // 15: etc_meisai.v1.CardService.ListCards:input_type -> etc_meisai.v1.ListCardsRequest
	2,  // 16: etc_meisai.v1.CardService.GetCard:output_type -> etc_meisai.v1.ETCCard
	2,  // 17: etc_meisai.v1.CardService.CreateCard:output_type -> etc_meisai.v1.ETCCard
	2,  // 18: etc_meisai.v1.CardService.UpdateCard:output_type -> etc_meisai.v1.ETCCard
	10, // 19: etc_meisai.v1.CardService.DeleteCard:output_type -> google.protobuf.Empty
	8,  // 20: etc_meisai.v1.CardService.ListCards:output_type -> etc_meisai.v1.ListCardsResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_card_proto_init() }
func file_card_proto_init() {
	if File_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_proto_rawDesc), len(file_card_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_card_proto_goTypes,
		DependencyIndexes: file_card_proto_depIdxs,
		EnumInfos:         file_card_proto_enumTypes,
		MessageInfos:      file_card_proto_msgTypes,
	}.Build()
	File_card_proto = out.File
	file_card_proto_goTypes = nil
	file_card_proto_depIdxs = nil
}
