// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: etc_service.proto

package etc_meisaiv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ETCMeisai core message
type ETCMeisai struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash           string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Date           string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Time           string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	CarType        string                 `protobuf:"bytes,5,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`
	CarNumber      string                 `protobuf:"bytes,6,opt,name=car_number,json=carNumber,proto3" json:"car_number,omitempty"`
	EntranceIc     string                 `protobuf:"bytes,7,opt,name=entrance_ic,json=entranceIc,proto3" json:"entrance_ic,omitempty"`
	ExitIc         string                 `protobuf:"bytes,8,opt,name=exit_ic,json=exitIc,proto3" json:"exit_ic,omitempty"`
	Distance       int32                  `protobuf:"varint,9,opt,name=distance,proto3" json:"distance,omitempty"`
	TollAmount     int32                  `protobuf:"varint,10,opt,name=toll_amount,json=tollAmount,proto3" json:"toll_amount,omitempty"`
	DiscountAmount int32                  `protobuf:"varint,11,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	FinalAmount    int32                  `protobuf:"varint,12,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	PaymentMethod  string                 `protobuf:"bytes,13,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	CardNumber     string                 `protobuf:"bytes,14,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	UserId         string                 `protobuf:"bytes,15,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ETCMeisai) Reset() {
	*x = ETCMeisai{}
	mi := &file_etc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETCMeisai) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETCMeisai) ProtoMessage() {}

func (x *ETCMeisai) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETCMeisai.ProtoReflect.Descriptor instead.
func (*ETCMeisai) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{0}
}

func (x *ETCMeisai) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ETCMeisai) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ETCMeisai) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ETCMeisai) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ETCMeisai) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *ETCMeisai) GetCarNumber() string {
	if x != nil {
		return x.CarNumber
	}
	return ""
}

func (x *ETCMeisai) GetEntranceIc() string {
	if x != nil {
		return x.EntranceIc
	}
	return ""
}

func (x *ETCMeisai) GetExitIc() string {
	if x != nil {
		return x.ExitIc
	}
	return ""
}

func (x *ETCMeisai) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *ETCMeisai) GetTollAmount() int32 {
	if x != nil {
		return x.TollAmount
	}
	return 0
}

func (x *ETCMeisai) GetDiscountAmount() int32 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *ETCMeisai) GetFinalAmount() int32 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *ETCMeisai) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *ETCMeisai) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *ETCMeisai) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ETCMeisai) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ETCMeisai) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request messages
type CreateETCMeisaiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EtcMeisai     *ETCMeisai             `protobuf:"bytes,1,opt,name=etc_meisai,json=etcMeisai,proto3" json:"etc_meisai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateETCMeisaiRequest) Reset() {
	*x = CreateETCMeisaiRequest{}
	mi := &file_etc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateETCMeisaiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateETCMeisaiRequest) ProtoMessage() {}

func (x *CreateETCMeisaiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateETCMeisaiRequest.ProtoReflect.Descriptor instead.
func (*CreateETCMeisaiRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateETCMeisaiRequest) GetEtcMeisai() *ETCMeisai {
	if x != nil {
		return x.EtcMeisai
	}
	return nil
}

type GetETCMeisaiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetETCMeisaiRequest) Reset() {
	*x = GetETCMeisaiRequest{}
	mi := &file_etc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetETCMeisaiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetETCMeisaiRequest) ProtoMessage() {}

func (x *GetETCMeisaiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetETCMeisaiRequest.ProtoReflect.Descriptor instead.
func (*GetETCMeisaiRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetETCMeisaiRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateETCMeisaiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EtcMeisai     *ETCMeisai             `protobuf:"bytes,2,opt,name=etc_meisai,json=etcMeisai,proto3" json:"etc_meisai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateETCMeisaiRequest) Reset() {
	*x = UpdateETCMeisaiRequest{}
	mi := &file_etc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateETCMeisaiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateETCMeisaiRequest) ProtoMessage() {}

func (x *UpdateETCMeisaiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateETCMeisaiRequest.ProtoReflect.Descriptor instead.
func (*UpdateETCMeisaiRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateETCMeisaiRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateETCMeisaiRequest) GetEtcMeisai() *ETCMeisai {
	if x != nil {
		return x.EtcMeisai
	}
	return nil
}

type DeleteETCMeisaiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteETCMeisaiRequest) Reset() {
	*x = DeleteETCMeisaiRequest{}
	mi := &file_etc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteETCMeisaiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteETCMeisaiRequest) ProtoMessage() {}

func (x *DeleteETCMeisaiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteETCMeisaiRequest.ProtoReflect.Descriptor instead.
func (*DeleteETCMeisaiRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteETCMeisaiRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListETCMeisaiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListETCMeisaiRequest) Reset() {
	*x = ListETCMeisaiRequest{}
	mi := &file_etc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListETCMeisaiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListETCMeisaiRequest) ProtoMessage() {}

func (x *ListETCMeisaiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListETCMeisaiRequest.ProtoReflect.Descriptor instead.
func (*ListETCMeisaiRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListETCMeisaiRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListETCMeisaiRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListETCMeisaiRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type BulkCreateETCMeisaiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EtcMeisaiList []*ETCMeisai           `protobuf:"bytes,1,rep,name=etc_meisai_list,json=etcMeisaiList,proto3" json:"etc_meisai_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateETCMeisaiRequest) Reset() {
	*x = BulkCreateETCMeisaiRequest{}
	mi := &file_etc_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateETCMeisaiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateETCMeisaiRequest) ProtoMessage() {}

func (x *BulkCreateETCMeisaiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateETCMeisaiRequest.ProtoReflect.Descriptor instead.
func (*BulkCreateETCMeisaiRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{6}
}

func (x *BulkCreateETCMeisaiRequest) GetEtcMeisaiList() []*ETCMeisai {
	if x != nil {
		return x.EtcMeisaiList
	}
	return nil
}

type BulkUpdateETCMeisaiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EtcMeisaiList []*ETCMeisai           `protobuf:"bytes,1,rep,name=etc_meisai_list,json=etcMeisaiList,proto3" json:"etc_meisai_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUpdateETCMeisaiRequest) Reset() {
	*x = BulkUpdateETCMeisaiRequest{}
	mi := &file_etc_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUpdateETCMeisaiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUpdateETCMeisaiRequest) ProtoMessage() {}

func (x *BulkUpdateETCMeisaiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUpdateETCMeisaiRequest.ProtoReflect.Descriptor instead.
func (*BulkUpdateETCMeisaiRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{7}
}

func (x *BulkUpdateETCMeisaiRequest) GetEtcMeisaiList() []*ETCMeisai {
	if x != nil {
		return x.EtcMeisaiList
	}
	return nil
}

type GetETCMeisaiByDateRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetETCMeisaiByDateRangeRequest) Reset() {
	*x = GetETCMeisaiByDateRangeRequest{}
	mi := &file_etc_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetETCMeisaiByDateRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetETCMeisaiByDateRangeRequest) ProtoMessage() {}

func (x *GetETCMeisaiByDateRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetETCMeisaiByDateRangeRequest.ProtoReflect.Descriptor instead.
func (*GetETCMeisaiByDateRangeRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetETCMeisaiByDateRangeRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetETCMeisaiByDateRangeRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetETCMeisaiByDateRangeRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetETCMeisaiByDateRangeRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetETCMeisaiByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetETCMeisaiByHashRequest) Reset() {
	*x = GetETCMeisaiByHashRequest{}
	mi := &file_etc_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetETCMeisaiByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetETCMeisaiByHashRequest) ProtoMessage() {}

func (x *GetETCMeisaiByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetETCMeisaiByHashRequest.ProtoReflect.Descriptor instead.
func (*GetETCMeisaiByHashRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetETCMeisaiByHashRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetUnmappedETCMeisaiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnmappedETCMeisaiRequest) Reset() {
	*x = GetUnmappedETCMeisaiRequest{}
	mi := &file_etc_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnmappedETCMeisaiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnmappedETCMeisaiRequest) ProtoMessage() {}

func (x *GetUnmappedETCMeisaiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnmappedETCMeisaiRequest.ProtoReflect.Descriptor instead.
func (*GetUnmappedETCMeisaiRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetUnmappedETCMeisaiRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetUnmappedETCMeisaiRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type CheckDuplicatesByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []string               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDuplicatesByHashRequest) Reset() {
	*x = CheckDuplicatesByHashRequest{}
	mi := &file_etc_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDuplicatesByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDuplicatesByHashRequest) ProtoMessage() {}

func (x *CheckDuplicatesByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDuplicatesByHashRequest.ProtoReflect.Descriptor instead.
func (*CheckDuplicatesByHashRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{11}
}

func (x *CheckDuplicatesByHashRequest) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type GenerateHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EtcMeisai     *ETCMeisai             `protobuf:"bytes,1,opt,name=etc_meisai,json=etcMeisai,proto3" json:"etc_meisai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateHashRequest) Reset() {
	*x = GenerateHashRequest{}
	mi := &file_etc_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateHashRequest) ProtoMessage() {}

func (x *GenerateHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateHashRequest.ProtoReflect.Descriptor instead.
func (*GenerateHashRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateHashRequest) GetEtcMeisai() *ETCMeisai {
	if x != nil {
		return x.EtcMeisai
	}
	return nil
}

type GetETCSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetETCSummaryRequest) Reset() {
	*x = GetETCSummaryRequest{}
	mi := &file_etc_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetETCSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetETCSummaryRequest) ProtoMessage() {}

func (x *GetETCSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetETCSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetETCSummaryRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetETCSummaryRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetETCSummaryRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetETCSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMonthlyStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlyStatsRequest) Reset() {
	*x = GetMonthlyStatsRequest{}
	mi := &file_etc_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyStatsRequest) ProtoMessage() {}

func (x *GetMonthlyStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMonthlyStatsRequest) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetMonthlyStatsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetMonthlyStatsRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *GetMonthlyStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Response messages
type ETCMeisaiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EtcMeisai     *ETCMeisai             `protobuf:"bytes,1,opt,name=etc_meisai,json=etcMeisai,proto3" json:"etc_meisai,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ETCMeisaiResponse) Reset() {
	*x = ETCMeisaiResponse{}
	mi := &file_etc_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETCMeisaiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETCMeisaiResponse) ProtoMessage() {}

func (x *ETCMeisaiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETCMeisaiResponse.ProtoReflect.Descriptor instead.
func (*ETCMeisaiResponse) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{15}
}

func (x *ETCMeisaiResponse) GetEtcMeisai() *ETCMeisai {
	if x != nil {
		return x.EtcMeisai
	}
	return nil
}

type ListETCMeisaiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EtcMeisaiList []*ETCMeisai           `protobuf:"bytes,1,rep,name=etc_meisai_list,json=etcMeisaiList,proto3" json:"etc_meisai_list,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListETCMeisaiResponse) Reset() {
	*x = ListETCMeisaiResponse{}
	mi := &file_etc_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListETCMeisaiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListETCMeisaiResponse) ProtoMessage() {}

func (x *ListETCMeisaiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListETCMeisaiResponse.ProtoReflect.Descriptor instead.
func (*ListETCMeisaiResponse) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListETCMeisaiResponse) GetEtcMeisaiList() []*ETCMeisai {
	if x != nil {
		return x.EtcMeisaiList
	}
	return nil
}

func (x *ListETCMeisaiResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListETCMeisaiResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type BulkCreateETCMeisaiResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CreatedEtcMeisaiList []*ETCMeisai           `protobuf:"bytes,1,rep,name=created_etc_meisai_list,json=createdEtcMeisaiList,proto3" json:"created_etc_meisai_list,omitempty"`
	SuccessCount         int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	ErrorCount           int32                  `protobuf:"varint,3,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	ErrorMessages        []string               `protobuf:"bytes,4,rep,name=error_messages,json=errorMessages,proto3" json:"error_messages,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BulkCreateETCMeisaiResponse) Reset() {
	*x = BulkCreateETCMeisaiResponse{}
	mi := &file_etc_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateETCMeisaiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateETCMeisaiResponse) ProtoMessage() {}

func (x *BulkCreateETCMeisaiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateETCMeisaiResponse.ProtoReflect.Descriptor instead.
func (*BulkCreateETCMeisaiResponse) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{17}
}

func (x *BulkCreateETCMeisaiResponse) GetCreatedEtcMeisaiList() []*ETCMeisai {
	if x != nil {
		return x.CreatedEtcMeisaiList
	}
	return nil
}

func (x *BulkCreateETCMeisaiResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BulkCreateETCMeisaiResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *BulkCreateETCMeisaiResponse) GetErrorMessages() []string {
	if x != nil {
		return x.ErrorMessages
	}
	return nil
}

type BulkUpdateETCMeisaiResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UpdatedEtcMeisaiList []*ETCMeisai           `protobuf:"bytes,1,rep,name=updated_etc_meisai_list,json=updatedEtcMeisaiList,proto3" json:"updated_etc_meisai_list,omitempty"`
	SuccessCount         int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	ErrorCount           int32                  `protobuf:"varint,3,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	ErrorMessages        []string               `protobuf:"bytes,4,rep,name=error_messages,json=errorMessages,proto3" json:"error_messages,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BulkUpdateETCMeisaiResponse) Reset() {
	*x = BulkUpdateETCMeisaiResponse{}
	mi := &file_etc_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUpdateETCMeisaiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUpdateETCMeisaiResponse) ProtoMessage() {}

func (x *BulkUpdateETCMeisaiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUpdateETCMeisaiResponse.ProtoReflect.Descriptor instead.
func (*BulkUpdateETCMeisaiResponse) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{18}
}

func (x *BulkUpdateETCMeisaiResponse) GetUpdatedEtcMeisaiList() []*ETCMeisai {
	if x != nil {
		return x.UpdatedEtcMeisaiList
	}
	return nil
}

func (x *BulkUpdateETCMeisaiResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BulkUpdateETCMeisaiResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *BulkUpdateETCMeisaiResponse) GetErrorMessages() []string {
	if x != nil {
		return x.ErrorMessages
	}
	return nil
}

type CheckDuplicatesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DuplicateHashes []string               `protobuf:"bytes,1,rep,name=duplicate_hashes,json=duplicateHashes,proto3" json:"duplicate_hashes,omitempty"`
	DuplicateCount  int32                  `protobuf:"varint,2,opt,name=duplicate_count,json=duplicateCount,proto3" json:"duplicate_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckDuplicatesResponse) Reset() {
	*x = CheckDuplicatesResponse{}
	mi := &file_etc_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDuplicatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDuplicatesResponse) ProtoMessage() {}

func (x *CheckDuplicatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDuplicatesResponse.ProtoReflect.Descriptor instead.
func (*CheckDuplicatesResponse) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{19}
}

func (x *CheckDuplicatesResponse) GetDuplicateHashes() []string {
	if x != nil {
		return x.DuplicateHashes
	}
	return nil
}

func (x *CheckDuplicatesResponse) GetDuplicateCount() int32 {
	if x != nil {
		return x.DuplicateCount
	}
	return 0
}

type GenerateHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateHashResponse) Reset() {
	*x = GenerateHashResponse{}
	mi := &file_etc_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateHashResponse) ProtoMessage() {}

func (x *GenerateHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateHashResponse.ProtoReflect.Descriptor instead.
func (*GenerateHashResponse) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateHashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetETCSummaryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalTransactions int32                  `protobuf:"varint,1,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalAmount       int64                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	TotalToll         int64                  `protobuf:"varint,3,opt,name=total_toll,json=totalToll,proto3" json:"total_toll,omitempty"`
	TotalDiscount     int64                  `protobuf:"varint,4,opt,name=total_discount,json=totalDiscount,proto3" json:"total_discount,omitempty"`
	MonthlySummaries  []*ETCMonthlySummary   `protobuf:"bytes,5,rep,name=monthly_summaries,json=monthlySummaries,proto3" json:"monthly_summaries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetETCSummaryResponse) Reset() {
	*x = GetETCSummaryResponse{}
	mi := &file_etc_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetETCSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetETCSummaryResponse) ProtoMessage() {}

func (x *GetETCSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetETCSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetETCSummaryResponse) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetETCSummaryResponse) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *GetETCSummaryResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetETCSummaryResponse) GetTotalToll() int64 {
	if x != nil {
		return x.TotalToll
	}
	return 0
}

func (x *GetETCSummaryResponse) GetTotalDiscount() int64 {
	if x != nil {
		return x.TotalDiscount
	}
	return 0
}

func (x *GetETCSummaryResponse) GetMonthlySummaries() []*ETCMonthlySummary {
	if x != nil {
		return x.MonthlySummaries
	}
	return nil
}

type GetMonthlyStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Year             int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month            int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	TransactionCount int32                  `protobuf:"varint,3,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	TotalAmount      int64                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	AverageAmount    int64                  `protobuf:"varint,5,opt,name=average_amount,json=averageAmount,proto3" json:"average_amount,omitempty"`
	DailyStats       []*ETCDailyStat        `protobuf:"bytes,6,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMonthlyStatsResponse) Reset() {
	*x = GetMonthlyStatsResponse{}
	mi := &file_etc_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyStatsResponse) ProtoMessage() {}

func (x *GetMonthlyStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyStatsResponse.ProtoReflect.Descriptor instead.
func (*GetMonthlyStatsResponse) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetMonthlyStatsResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetMonthlyStatsResponse) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *GetMonthlyStatsResponse) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *GetMonthlyStatsResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetMonthlyStatsResponse) GetAverageAmount() int64 {
	if x != nil {
		return x.AverageAmount
	}
	return 0
}

func (x *GetMonthlyStatsResponse) GetDailyStats() []*ETCDailyStat {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

type ETCMonthlySummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Year             int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month            int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	TransactionCount int32                  `protobuf:"varint,3,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	TotalAmount      int64                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ETCMonthlySummary) Reset() {
	*x = ETCMonthlySummary{}
	mi := &file_etc_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETCMonthlySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETCMonthlySummary) ProtoMessage() {}

func (x *ETCMonthlySummary) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETCMonthlySummary.ProtoReflect.Descriptor instead.
func (*ETCMonthlySummary) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{23}
}

func (x *ETCMonthlySummary) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ETCMonthlySummary) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *ETCMonthlySummary) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *ETCMonthlySummary) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ETCDailyStat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Day              int32                  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	TransactionCount int32                  `protobuf:"varint,2,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	TotalAmount      int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ETCDailyStat) Reset() {
	*x = ETCDailyStat{}
	mi := &file_etc_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ETCDailyStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ETCDailyStat) ProtoMessage() {}

func (x *ETCDailyStat) ProtoReflect() protoreflect.Message {
	mi := &file_etc_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ETCDailyStat.ProtoReflect.Descriptor instead.
func (*ETCDailyStat) Descriptor() ([]byte, []int) {
	return file_etc_service_proto_rawDescGZIP(), []int{24}
}

func (x *ETCDailyStat) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *ETCDailyStat) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *ETCDailyStat) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

var File_etc_service_proto protoreflect.FileDescriptor

const file_etc_service_proto_rawDesc = "" +
	"\n" +
	"\x11etc_service.proto\x12\retc_meisai.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x04\n" +
	"\tETCMeisai\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\x12\x19\n" +
	"\bcar_type\x18\x05 \x01(\tR\acarType\x12\x1d\n" +
	"\n" +
	"car_number\x18\x06 \x01(\tR\tcarNumber\x12\x1f\n" +
	"\ventrance_ic\x18\a \x01(\tR\n" +
	"entranceIc\x12\x17\n" +
	"\aexit_ic\x18\b \x01(\tR\x06exitIc\x12\x1a\n" +
	"\bdistance\x18\t \x01(\x05R\bdistance\x12\x1f\n" +
	"\vtoll_amount\x18\n" +
	" \x01(\x05R\n" +
	"tollAmount\x12'\n" +
	"\x0fdiscount_amount\x18\v \x01(\x05R\x0ediscountAmount\x12!\n" +
	"\ffinal_amount\x18\f \x01(\x05R\vfinalAmount\x12%\n" +
	"\x0epayment_method\x18\r \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vcard_number\x18\x0e \x01(\tR\n" +
	"cardNumber\x12\x17\n" +
	"\auser_id\x18\x0f \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Q\n" +
	"\x16CreateETCMeisaiRequest\x127\n" +
	"\n" +
	"etc_meisai\x18\x01 \x01(\v2\x18.etc_meisai.v1.ETCMeisaiR\tetcMeisai\"%\n" +
	"\x13GetETCMeisaiRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"a\n" +
	"\x16UpdateETCMeisaiRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x127\n" +
	"\n" +
	"etc_meisai\x18\x02 \x01(\v2\x18.etc_meisai.v1.ETCMeisaiR\tetcMeisai\"(\n" +
	"\x16DeleteETCMeisaiRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"j\n" +
	"\x14ListETCMeisaiRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"^\n" +
	"\x1aBulkCreateETCMeisaiRequest\x12@\n" +
	"\x0fetc_meisai_list\x18\x01 \x03(\v2\x18.etc_meisai.v1.ETCMeisaiR\retcMeisaiList\"^\n" +
	"\x1aBulkUpdateETCMeisaiRequest\x12@\n" +
	"\x0fetc_meisai_list\x18\x01 \x03(\v2\x18.etc_meisai.v1.ETCMeisaiR\retcMeisaiList\"\x96\x01\n" +
	"\x1eGetETCMeisaiByDateRangeRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"/\n" +
	"\x19GetETCMeisaiByHashRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"Y\n" +
	"\x1bGetUnmappedETCMeisaiRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"6\n" +
	"\x1cCheckDuplicatesByHashRequest\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\tR\x06hashes\"N\n" +
	"\x13GenerateHashRequest\x127\n" +
	"\n" +
	"etc_meisai\x18\x01 \x01(\v2\x18.etc_meisai.v1.ETCMeisaiR\tetcMeisai\"i\n" +
	"\x14GetETCSummaryRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"[\n" +
	"\x16GetMonthlyStatsRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"L\n" +
	"\x11ETCMeisaiResponse\x127\n" +
	"\n" +
	"etc_meisai\x18\x01 \x01(\v2\x18.etc_meisai.v1.ETCMeisaiR\tetcMeisai\"\xa2\x01\n" +
	"\x15ListETCMeisaiResponse\x12@\n" +
	"\x0fetc_meisai_list\x18\x01 \x03(\v2\x18.etc_meisai.v1.ETCMeisaiR\retcMeisaiList\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xdb\x01\n" +
	"\x1bBulkCreateETCMeisaiResponse\x12O\n" +
	"\x17created_etc_meisai_list\x18\x01 \x03(\v2\x18.etc_meisai.v1.ETCMeisaiR\x14createdEtcMeisaiList\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12\x1f\n" +
	"\verror_count\x18\x03 \x01(\x05R\n" +
	"errorCount\x12%\n" +
	"\x0eerror_messages\x18\x04 \x03(\tR\rerrorMessages\"\xdb\x01\n" +
	"\x1bBulkUpdateETCMeisaiResponse\x12O\n" +
	"\x17updated_etc_meisai_list\x18\x01 \x03(\v2\x18.etc_meisai.v1.ETCMeisaiR\x14updatedEtcMeisaiList\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12\x1f\n" +
	"\verror_count\x18\x03 \x01(\x05R\n" +
	"errorCount\x12%\n" +
	"\x0eerror_messages\x18\x04 \x03(\tR\rerrorMessages\"m\n" +
	"\x17CheckDuplicatesResponse\x12)\n" +
	"\x10duplicate_hashes\x18\x01 \x03(\tR\x0fduplicateHashes\x12'\n" +
	"\x0fduplicate_count\x18\x02 \x01(\x05R\x0eduplicateCount\"*\n" +
	"\x14GenerateHashResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xfe\x01\n" +
	"\x15GetETCSummaryResponse\x12-\n" +
	"\x12total_transactions\x18\x01 \x01(\x05R\x11totalTransactions\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x03R\vtotalAmount\x12\x1d\n" +
	"\n" +
	"total_toll\x18\x03 \x01(\x03R\ttotalToll\x12%\n" +
	"\x0etotal_discount\x18\x04 \x01(\x03R\rtotalDiscount\x12M\n" +
	"\x11monthly_summaries\x18\x05 \x03(\v2 .etc_meisai.v1.ETCMonthlySummaryR\x10monthlySummaries\"\xf8\x01\n" +
	"\x17GetMonthlyStatsResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12+\n" +
	"\x11transaction_count\x18\x03 \x01(\x05R\x10transactionCount\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x03R\vtotalAmount\x12%\n" +
	"\x0eaverage_amount\x18\x05 \x01(\x03R\raverageAmount\x12<\n" +
	"\vdaily_stats\x18\x06 \x03(\v2\x1b.etc_meisai.v1.ETCDailyStatR\n" +
	"dailyStats\"\x8d\x01\n" +
	"\x11ETCMonthlySummary\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12+\n" +
	"\x11transaction_count\x18\x03 \x01(\x05R\x10transactionCount\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x03R\vtotalAmount\"p\n" +
	"\fETCDailyStat\x12\x10\n" +
	"\x03day\x18\x01 \x01(\x05R\x03day\x12+\n" +
	"\x11transaction_count\x18\x02 \x01(\x05R\x10transactionCount\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount2\xd1\f\n" +
	"\n" +
	"ETCService\x12y\n" +
	"\x0fCreateETCMeisai\x12%.etc_meisai.v1.CreateETCMeisaiRequest\x1a .etc_meisai.v1.ETCMeisaiResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/etc/meisai\x12u\n" +
	"\fGetETCMeisai\x12\".etc_meisai.v1.GetETCMeisaiRequest\x1a .etc_meisai.v1.ETCMeisaiResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/etc/meisai/{id}\x12\x87\x01\n" +
	"\x0fUpdateETCMeisai\x12%.etc_meisai.v1.UpdateETCMeisaiRequest\x1a .etc_meisai.v1.ETCMeisaiResponse\"+\x82\xd3\xe4\x93\x02%:\n" +
	"etc_meisai\x1a\x17/api/v1/etc/meisai/{id}\x12q\n" +
	"\x0fDeleteETCMeisai\x12%.etc_meisai.v1.DeleteETCMeisaiRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/api/v1/etc/meisai/{id}\x12v\n" +
	"\rListETCMeisai\x12#.etc_meisai.v1.ListETCMeisaiRequest\x1a$.etc_meisai.v1.ListETCMeisaiResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/etc/meisai\x12l\n" +
	"\x13BulkCreateETCMeisai\x12).etc_meisai.v1.BulkCreateETCMeisaiRequest\x1a*.etc_meisai.v1.BulkCreateETCMeisaiResponse\x12l\n" +
	"\x13BulkUpdateETCMeisai\x12).etc_meisai.v1.BulkUpdateETCMeisaiRequest\x1a*.etc_meisai.v1.BulkUpdateETCMeisaiResponse\x12n\n" +
	"\x17GetETCMeisaiByDateRange\x12-.etc_meisai.v1.GetETCMeisaiByDateRangeRequest\x1a$.etc_meisai.v1.ListETCMeisaiResponse\x12`\n" +
	"\x12GetETCMeisaiByHash\x12(.etc_meisai.v1.GetETCMeisaiByHashRequest\x1a .etc_meisai.v1.ETCMeisaiResponse\x12h\n" +
	"\x14GetUnmappedETCMeisai\x12*.etc_meisai.v1.GetUnmappedETCMeisaiRequest\x1a$.etc_meisai.v1.ListETCMeisaiResponse\x12l\n" +
	"\x15CheckDuplicatesByHash\x12+.etc_meisai.v1.CheckDuplicatesByHashRequest\x1a&.etc_meisai.v1.CheckDuplicatesResponse\x12W\n" +
	"\fGenerateHash\x12\".etc_meisai.v1.GenerateHashRequest\x1a#.etc_meisai.v1.GenerateHashResponse\x12w\n" +
	"\rGetETCSummary\x12#.etc_meisai.v1.GetETCSummaryRequest\x1a$.etc_meisai.v1.GetETCSummaryResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/etc/summary\x12\x83\x01\n" +
	"\x0fGetMonthlyStats\x12%.etc_meisai.v1.GetMonthlyStatsRequest\x1a&.etc_meisai.v1.GetMonthlyStatsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/etc/stats/monthlyB?Z=github.com/yhonda-ohishi/db-handler-server/proto;etc_meisaiv1b\x06proto3"

var (
	file_etc_service_proto_rawDescOnce sync.Once
	file_etc_service_proto_rawDescData []byte
)

func file_etc_service_proto_rawDescGZIP() []byte {
	file_etc_service_proto_rawDescOnce.Do(func() {
		file_etc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_etc_service_proto_rawDesc), len(file_etc_service_proto_rawDesc)))
	})
	return file_etc_service_proto_rawDescData
}

var file_etc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_etc_service_proto_goTypes = []any{
	(*ETCMeisai)(nil),                      // 0: etc_meisai.v1.ETCMeisai
	(*CreateETCMeisaiRequest)(nil),         // 1: etc_meisai.v1.CreateETCMeisaiRequest
	(*GetETCMeisaiRequest)(nil),            // 2: etc_meisai.v1.GetETCMeisaiRequest
	(*UpdateETCMeisaiRequest)(nil),         // 3: etc_meisai.v1.UpdateETCMeisaiRequest
	(*DeleteETCMeisaiRequest)(nil),         // 4: etc_meisai.v1.DeleteETCMeisaiRequest
	(*ListETCMeisaiRequest)(nil),           // 5: etc_meisai.v1.ListETCMeisaiRequest
	(*BulkCreateETCMeisaiRequest)(nil),     // 6: etc_meisai.v1.BulkCreateETCMeisaiRequest
	(*BulkUpdateETCMeisaiRequest)(nil),     // 7: etc_meisai.v1.BulkUpdateETCMeisaiRequest
	(*GetETCMeisaiByDateRangeRequest)(nil), // 8: etc_meisai.v1.GetETCMeisaiByDateRangeRequest
	(*GetETCMeisaiByHashRequest)(nil),      // 9: etc_meisai.v1.GetETCMeisaiByHashRequest
	(*GetUnmappedETCMeisaiRequest)(nil),    // 10: etc_meisai.v1.GetUnmappedETCMeisaiRequest
	(*CheckDuplicatesByHashRequest)(nil),   // 11: etc_meisai.v1.CheckDuplicatesByHashRequest
	(*GenerateHashRequest)(nil),            // 12: etc_meisai.v1.GenerateHashRequest
	(*GetETCSummaryRequest)(nil),           // 13: etc_meisai.v1.GetETCSummaryRequest
	(*GetMonthlyStatsRequest)(nil),         // 14: etc_meisai.v1.GetMonthlyStatsRequest
	(*ETCMeisaiResponse)(nil),              // 15: etc_meisai.v1.ETCMeisaiResponse
	(*ListETCMeisaiResponse)(nil),          // 16: etc_meisai.v1.ListETCMeisaiResponse
	(*BulkCreateETCMeisaiResponse)(nil),    // 17: etc_meisai.v1.BulkCreateETCMeisaiResponse
	(*BulkUpdateETCMeisaiResponse)(nil),    // 18: etc_meisai.v1.BulkUpdateETCMeisaiResponse
	(*CheckDuplicatesResponse)(nil),        // 19: etc_meisai.v1.CheckDuplicatesResponse
	(*GenerateHashResponse)(nil),           // 20: etc_meisai.v1.GenerateHashResponse
	(*GetETCSummaryResponse)(nil),          // 21: etc_meisai.v1.GetETCSummaryResponse
	(*GetMonthlyStatsResponse)(nil),        // 22: etc_meisai.v1.GetMonthlyStatsResponse
	(*ETCMonthlySummary)(nil),              // 23: etc_meisai.v1.ETCMonthlySummary
	(*ETCDailyStat)(nil),                   // 24: etc_meisai.v1.ETCDailyStat
	(*timestamppb.Timestamp)(nil),          // 25: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 26: google.protobuf.Empty
}
var file_etc_service_proto_depIdxs = []int32{
	25, // 0: etc_meisai.v1.ETCMeisai.created_at:type_name -> google.protobuf.Timestamp
	25, // 1: etc_meisai.v1.ETCMeisai.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: etc_meisai.v1.CreateETCMeisaiRequest.etc_meisai:type_name -> etc_meisai.v1.ETCMeisai
	0,  // 3: etc_meisai.v1.UpdateETCMeisaiRequest.etc_meisai:type_name -> etc_meisai.v1.ETCMeisai
	0,  // 4: etc_meisai.v1.BulkCreateETCMeisaiRequest.etc_meisai_list:type_name -> etc_meisai.v1.ETCMeisai
	0,  // 5: etc_meisai.v1.BulkUpdateETCMeisaiRequest.etc_meisai_list:type_name -> etc_meisai.v1.ETCMeisai
	0,  // 6: etc_meisai.v1.GenerateHashRequest.etc_meisai:type_name -> etc_meisai.v1.ETCMeisai
	0,  // 7: etc_meisai.v1.ETCMeisaiResponse.etc_meisai:type_name -> etc_meisai.v1.ETCMeisai
	0,  // 8: etc_meisai.v1.ListETCMeisaiResponse.etc_meisai_list:type_name -> etc_meisai.v1.ETCMeisai
	0,  // 9: etc_meisai.v1.BulkCreateETCMeisaiResponse.created_etc_meisai_list:type_name -> etc_meisai.v1.ETCMeisai
	0,  // 10: etc_meisai.v1.BulkUpdateETCMeisaiResponse.updated_etc_meisai_list:type_name -> etc_meisai.v1.ETCMeisai
	23, // 11: etc_meisai.v1.GetETCSummaryResponse.monthly_summaries:type_name -> etc_meisai.v1.ETCMonthlySummary
	24, // 12: etc_meisai.v1.GetMonthlyStatsResponse.daily_stats:type_name -> etc_meisai.v1.ETCDailyStat
	1,  // 13: etc_meisai.v1.ETCService.CreateETCMeisai:input_type -> etc_meisai.v1.CreateETCMeisaiRequest
	2,  // 14: etc_meisai.v1.ETCService.GetETCMeisai:input_type -> etc_meisai.v1.GetETCMeisaiRequest
	3,  // 15: etc_meisai.v1.ETCService.UpdateETCMeisai:input_type -> etc_meisai.v1.UpdateETCMeisaiRequest
	4,  // 16: etc_meisai.v1.ETCService.DeleteETCMeisai:input_type -> etc_meisai.v1.DeleteETCMeisaiRequest
	5,  // 17: etc_meisai.v1.ETCService.ListETCMeisai:input_type -> etc_meisai.v1.ListETCMeisaiRequest
	6,  // 18: etc_meisai.v1.ETCService.BulkCreateETCMeisai:input_type -> etc_meisai.v1.BulkCreateETCMeisaiRequest
	7,  // 19: etc_meisai.v1.ETCService.BulkUpdateETCMeisai:input_type -> etc_meisai.v1.BulkUpdateETCMeisaiRequest
	8,  // 20: etc_meisai.v1.ETCService.GetETCMeisaiByDateRange:input_type -> etc_meisai.v1.GetETCMeisaiByDateRangeRequest
	9,  // 21: etc_meisai.v1.ETCService.GetETCMeisaiByHash:input_type -> etc_meisai.v1.GetETCMeisaiByHashRequest
	10, // 22: etc_meisai.v1.ETCService.GetUnmappedETCMeisai:input_type -> etc_meisai.v1.GetUnmappedETCMeisaiRequest
	11, // 23: etc_meisai.v1.ETCService.CheckDuplicatesByHash:input_type -> etc_meisai.v1.CheckDuplicatesByHashRequest
	12, // 24: etc_meisai.v1.ETCService.GenerateHash:input_type -> etc_meisai.v1.GenerateHashRequest
	13, // 25: etc_meisai.v1.ETCService.GetETCSummary:input_type -> etc_meisai.v1.GetETCSummaryRequest
	14, // 26: etc_meisai.v1.ETCService.GetMonthlyStats:input_type -> etc_meisai.v1.GetMonthlyStatsRequest
	15, // 27: etc_meisai.v1.ETCService.CreateETCMeisai:output_type -> etc_meisai.v1.ETCMeisaiResponse
	15, // 28: etc_meisai.v1.ETCService.GetETCMeisai:output_type -> etc_meisai.v1.ETCMeisaiResponse
	15, // 29: etc_meisai.v1.ETCService.UpdateETCMeisai:output_type -> etc_meisai.v1.ETCMeisaiResponse
	26, // 30: etc_meisai.v1.ETCService.DeleteETCMeisai:output_type -> google.protobuf.Empty
	16, // 31: etc_meisai.v1.ETCService.ListETCMeisai:output_type -> etc_meisai.v1.ListETCMeisaiResponse
	17, // 32: etc_meisai.v1.ETCService.BulkCreateETCMeisai:output_type -> etc_meisai.v1.BulkCreateETCMeisaiResponse
	18, // 33: etc_meisai.v1.ETCService.BulkUpdateETCMeisai:output_type -> etc_meisai.v1.BulkUpdateETCMeisaiResponse
	16, // 34: etc_meisai.v1.ETCService.GetETCMeisaiByDateRange:output_type -> etc_meisai.v1.ListETCMeisaiResponse
	15, // 35: etc_meisai.v1.ETCService.GetETCMeisaiByHash:output_type -> etc_meisai.v1.ETCMeisaiResponse
	16, // 36: etc_meisai.v1.ETCService.GetUnmappedETCMeisai:output_type -> etc_meisai.v1.ListETCMeisaiResponse
	19, // 37: etc_meisai.v1.ETCService.CheckDuplicatesByHash:output_type -> etc_meisai.v1.CheckDuplicatesResponse
	20, // 38: etc_meisai.v1.ETCService.GenerateHash:output_type -> etc_meisai.v1.GenerateHashResponse
	21, // 39: etc_meisai.v1.ETCService.GetETCSummary:output_type -> etc_meisai.v1.GetETCSummaryResponse
	22, // 40: etc_meisai.v1.ETCService.GetMonthlyStats:output_type -> etc_meisai.v1.GetMonthlyStatsResponse
	27, // [27:41] is the sub-list for method output_type
	13, // [13:27] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_etc_service_proto_init() }
func file_etc_service_proto_init() {
	if File_etc_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_etc_service_proto_rawDesc), len(file_etc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_etc_service_proto_goTypes,
		DependencyIndexes: file_etc_service_proto_depIdxs,
		MessageInfos:      file_etc_service_proto_msgTypes,
	}.Build()
	File_etc_service_proto = out.File
	file_etc_service_proto_goTypes = nil
	file_etc_service_proto_depIdxs = nil
}
