// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: payment.proto

package etc_meisaiv1

import (
	_ "github.com/yhonda-ohishi/db-handler-server/google/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED   PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD   PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_BANK_TRANSFER PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_AUTO_DEBIT    PaymentMethod = 3
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CREDIT_CARD",
		2: "PAYMENT_METHOD_BANK_TRANSFER",
		3: "PAYMENT_METHOD_AUTO_DEBIT",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED":   0,
		"PAYMENT_METHOD_CREDIT_CARD":   1,
		"PAYMENT_METHOD_BANK_TRANSFER": 2,
		"PAYMENT_METHOD_AUTO_DEBIT":    3,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentProcessingStatus int32

const (
	PaymentProcessingStatus_PAYMENT_PROCESSING_STATUS_UNSPECIFIED PaymentProcessingStatus = 0
	PaymentProcessingStatus_PAYMENT_PROCESSING_STATUS_PENDING     PaymentProcessingStatus = 1
	PaymentProcessingStatus_PAYMENT_PROCESSING_STATUS_PROCESSING  PaymentProcessingStatus = 2
	PaymentProcessingStatus_PAYMENT_PROCESSING_STATUS_COMPLETED   PaymentProcessingStatus = 3
	PaymentProcessingStatus_PAYMENT_PROCESSING_STATUS_FAILED      PaymentProcessingStatus = 4
)

// Enum value maps for PaymentProcessingStatus.
var (
	PaymentProcessingStatus_name = map[int32]string{
		0: "PAYMENT_PROCESSING_STATUS_UNSPECIFIED",
		1: "PAYMENT_PROCESSING_STATUS_PENDING",
		2: "PAYMENT_PROCESSING_STATUS_PROCESSING",
		3: "PAYMENT_PROCESSING_STATUS_COMPLETED",
		4: "PAYMENT_PROCESSING_STATUS_FAILED",
	}
	PaymentProcessingStatus_value = map[string]int32{
		"PAYMENT_PROCESSING_STATUS_UNSPECIFIED": 0,
		"PAYMENT_PROCESSING_STATUS_PENDING":     1,
		"PAYMENT_PROCESSING_STATUS_PROCESSING":  2,
		"PAYMENT_PROCESSING_STATUS_COMPLETED":   3,
		"PAYMENT_PROCESSING_STATUS_FAILED":      4,
	}
)

func (x PaymentProcessingStatus) Enum() *PaymentProcessingStatus {
	p := new(PaymentProcessingStatus)
	*p = x
	return p
}

func (x PaymentProcessingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentProcessingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentProcessingStatus) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[1]
}

func (x PaymentProcessingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentProcessingStatus.Descriptor instead.
func (PaymentProcessingStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

// Payment represents a payment record
type Payment struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Id              string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionIds  []string                `protobuf:"bytes,3,rep,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"`
	TotalAmount     int64                   `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PaymentMethod   PaymentMethod           `protobuf:"varint,5,opt,name=payment_method,json=paymentMethod,proto3,enum=etc_meisai.v1.PaymentMethod" json:"payment_method,omitempty"`
	PaymentDate     *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	Status          PaymentProcessingStatus `protobuf:"varint,7,opt,name=status,proto3,enum=etc_meisai.v1.PaymentProcessingStatus" json:"status,omitempty"`
	ReferenceNumber string                  `protobuf:"bytes,8,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetTransactionIds() []string {
	if x != nil {
		return x.TransactionIds
	}
	return nil
}

func (x *Payment) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Payment) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Payment) GetPaymentDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PaymentDate
	}
	return nil
}

func (x *Payment) GetStatus() PaymentProcessingStatus {
	if x != nil {
		return x.Status
	}
	return PaymentProcessingStatus_PAYMENT_PROCESSING_STATUS_UNSPECIFIED
}

func (x *Payment) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

// MonthlyStatement represents monthly billing statement
type MonthlyStatement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardId         string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Year           int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Month          int32                  `protobuf:"varint,5,opt,name=month,proto3" json:"month,omitempty"`
	TotalTrips     int32                  `protobuf:"varint,6,opt,name=total_trips,json=totalTrips,proto3" json:"total_trips,omitempty"`
	TotalDistance  float64                `protobuf:"fixed64,7,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	TotalAmount    int64                  `protobuf:"varint,8,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	DiscountAmount int64                  `protobuf:"varint,9,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	FinalAmount    int64                  `protobuf:"varint,10,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	GeneratedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	PaymentDueDate *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=payment_due_date,json=paymentDueDate,proto3" json:"payment_due_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MonthlyStatement) Reset() {
	*x = MonthlyStatement{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyStatement) ProtoMessage() {}

func (x *MonthlyStatement) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyStatement.ProtoReflect.Descriptor instead.
func (*MonthlyStatement) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *MonthlyStatement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MonthlyStatement) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MonthlyStatement) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *MonthlyStatement) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MonthlyStatement) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *MonthlyStatement) GetTotalTrips() int32 {
	if x != nil {
		return x.TotalTrips
	}
	return 0
}

func (x *MonthlyStatement) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *MonthlyStatement) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *MonthlyStatement) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *MonthlyStatement) GetFinalAmount() int64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *MonthlyStatement) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *MonthlyStatement) GetPaymentDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PaymentDueDate
	}
	return nil
}

// Request messages
type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreatePaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionIds []string               `protobuf:"bytes,2,rep,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"`
	TotalAmount    int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PaymentMethod  PaymentMethod          `protobuf:"varint,4,opt,name=payment_method,json=paymentMethod,proto3,enum=etc_meisai.v1.PaymentMethod" json:"payment_method,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePaymentRequest) GetTransactionIds() []string {
	if x != nil {
		return x.TransactionIds
	}
	return nil
}

func (x *CreatePaymentRequest) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreatePaymentRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

type GetMonthlyStatementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlyStatementRequest) Reset() {
	*x = GetMonthlyStatementRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyStatementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyStatementRequest) ProtoMessage() {}

func (x *GetMonthlyStatementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyStatementRequest.ProtoReflect.Descriptor instead.
func (*GetMonthlyStatementRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetMonthlyStatementRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMonthlyStatementRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetMonthlyStatementRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type ListPaymentsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserId        string                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        PaymentProcessingStatus `protobuf:"varint,2,opt,name=status,proto3,enum=etc_meisai.v1.PaymentProcessingStatus" json:"status,omitempty"`
	PageSize      int32                   `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                  `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ListPaymentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListPaymentsRequest) GetStatus() PaymentProcessingStatus {
	if x != nil {
		return x.Status
	}
	return PaymentProcessingStatus_PAYMENT_PROCESSING_STATUS_UNSPECIFIED
}

func (x *ListPaymentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPaymentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ListPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListPaymentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\retc_meisai.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0ftransaction_ids\x18\x03 \x03(\tR\x0etransactionIds\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x03R\vtotalAmount\x12C\n" +
	"\x0epayment_method\x18\x05 \x01(\x0e2\x1c.etc_meisai.v1.PaymentMethodR\rpaymentMethod\x12=\n" +
	"\fpayment_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vpaymentDate\x12>\n" +
	"\x06status\x18\a \x01(\x0e2&.etc_meisai.v1.PaymentProcessingStatusR\x06status\x12)\n" +
	"\x10reference_number\x18\b \x01(\tR\x0freferenceNumber\"\xba\x03\n" +
	"\x10MonthlyStatement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x05 \x01(\x05R\x05month\x12\x1f\n" +
	"\vtotal_trips\x18\x06 \x01(\x05R\n" +
	"totalTrips\x12%\n" +
	"\x0etotal_distance\x18\a \x01(\x01R\rtotalDistance\x12!\n" +
	"\ftotal_amount\x18\b \x01(\x03R\vtotalAmount\x12'\n" +
	"\x0fdiscount_amount\x18\t \x01(\x03R\x0ediscountAmount\x12!\n" +
	"\ffinal_amount\x18\n" +
	" \x01(\x03R\vfinalAmount\x12=\n" +
	"\fgenerated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12D\n" +
	"\x10payment_due_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0epaymentDueDate\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc0\x01\n" +
	"\x14CreatePaymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0ftransaction_ids\x18\x02 \x03(\tR\x0etransactionIds\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\x12C\n" +
	"\x0epayment_method\x18\x04 \x01(\x0e2\x1c.etc_meisai.v1.PaymentMethodR\rpaymentMethod\"_\n" +
	"\x1aGetMonthlyStatementRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"\xaa\x01\n" +
	"\x13ListPaymentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2&.etc_meisai.v1.PaymentProcessingStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"r\n" +
	"\x14ListPaymentsResponse\x122\n" +
	"\bpayments\x18\x01 \x03(\v2\x16.etc_meisai.v1.PaymentR\bpayments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*\x90\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x01\x12 \n" +
	"\x1cPAYMENT_METHOD_BANK_TRANSFER\x10\x02\x12\x1d\n" +
	"\x19PAYMENT_METHOD_AUTO_DEBIT\x10\x03*\xe4\x01\n" +
	"\x17PaymentProcessingStatus\x12)\n" +
	"%PAYMENT_PROCESSING_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!PAYMENT_PROCESSING_STATUS_PENDING\x10\x01\x12(\n" +
	"$PAYMENT_PROCESSING_STATUS_PROCESSING\x10\x02\x12'\n" +
	"#PAYMENT_PROCESSING_STATUS_COMPLETED\x10\x03\x12$\n" +
	" PAYMENT_PROCESSING_STATUS_FAILED\x10\x042\xee\x03\n" +
	"\x0ePaymentService\x12e\n" +
	"\n" +
	"GetPayment\x12 .etc_meisai.v1.GetPaymentRequest\x1a\x16.etc_meisai.v1.Payment\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/payments/{id}\x12i\n" +
	"\rCreatePayment\x12#.etc_meisai.v1.CreatePaymentRequest\x1a\x16.etc_meisai.v1.Payment\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/payments\x12q\n" +
	"\fListPayments\x12\".etc_meisai.v1.ListPaymentsRequest\x1a#.etc_meisai.v1.ListPaymentsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/payments\x12\x96\x01\n" +
	"\x13GetMonthlyStatement\x12).etc_meisai.v1.GetMonthlyStatementRequest\x1a\x1f.etc_meisai.v1.MonthlyStatement\"3\x82\xd3\xe4\x93\x02-\x12+/api/v1/statements/{user_id}/{year}/{month}B\xab\x01\n" +
	"\x11com.etc_meisai.v1B\fPaymentProtoP\x01Z7github.com/yhonda-ohishi/db-handler-server;etc_meisaiv1\xa2\x02\x03EXX\xaa\x02\fEtcMeisai.V1\xca\x02\fEtcMeisai\\V1\xe2\x02\x18EtcMeisai\\V1\\GPBMetadata\xea\x02\rEtcMeisai::V1b\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_payment_proto_goTypes = []any{
	(PaymentMethod)(0),                 // 0: etc_meisai.v1.PaymentMethod
	(PaymentProcessingStatus)(0),       // 1: etc_meisai.v1.PaymentProcessingStatus
	(*Payment)(nil),                    // 2: etc_meisai.v1.Payment
	(*MonthlyStatement)(nil),           // 3: etc_meisai.v1.MonthlyStatement
	(*GetPaymentRequest)(nil),          // 4: etc_meisai.v1.GetPaymentRequest
	(*CreatePaymentRequest)(nil),       // 5: etc_meisai.v1.CreatePaymentRequest
	(*GetMonthlyStatementRequest)(nil), // 6: etc_meisai.v1.GetMonthlyStatementRequest
	(*ListPaymentsRequest)(nil),        // 7: etc_meisai.v1.ListPaymentsRequest
	(*ListPaymentsResponse)(nil),       // 8: etc_meisai.v1.ListPaymentsResponse
	(*timestamppb.Timestamp)(nil),      // 9: google.protobuf.Timestamp
}
var file_payment_proto_depIdxs = []int32{
	0,  // 0: etc_meisai.v1.Payment.payment_method:type_name -> etc_meisai.v1.PaymentMethod
	9,  // 1: etc_meisai.v1.Payment.payment_date:type_name -> google.protobuf.Timestamp
	1,  // 2: etc_meisai.v1.Payment.status:type_name -> etc_meisai.v1.PaymentProcessingStatus
	9,  // 3: etc_meisai.v1.MonthlyStatement.generated_at:type_name -> google.protobuf.Timestamp
	9,  // 4: etc_meisai.v1.MonthlyStatement.payment_due_date:type_name -> google.protobuf.Timestamp
	0,  // 5: etc_meisai.v1.CreatePaymentRequest.payment_method:type_name -> etc_meisai.v1.PaymentMethod
	1,  // 6: etc_meisai.v1.ListPaymentsRequest.status:type_name -> etc_meisai.v1.PaymentProcessingStatus
	2,  // 7: etc_meisai.v1.ListPaymentsResponse.payments:type_name -> etc_meisai.v1.Payment
	4,  // 8: etc_meisai.v1.PaymentService.GetPayment:input_type -> etc_meisai.v1.GetPaymentRequest
	5,  // 9: etc_meisai.v1.PaymentService.CreatePayment:input_type -> etc_meisai.v1.CreatePaymentRequest
	7,  // 10: etc_meisai.v1.PaymentService.ListPayments:input_type -> etc_meisai.v1.ListPaymentsRequest
	6,  // 11: etc_meisai.v1.PaymentService.GetMonthlyStatement:input_type -> etc_meisai.v1.GetMonthlyStatementRequest
	2,  // 12: etc_meisai.v1.PaymentService.GetPayment:output_type -> etc_meisai.v1.Payment
	2,  // 13: etc_meisai.v1.PaymentService.CreatePayment:output_type -> etc_meisai.v1.Payment
	8,  // 14: etc_meisai.v1.PaymentService.ListPayments:output_type -> etc_meisai.v1.ListPaymentsResponse
	3,  // 15: etc_meisai.v1.PaymentService.GetMonthlyStatement:output_type -> etc_meisai.v1.MonthlyStatement
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
