// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: transaction.proto

package etc_meisaiv1

import (
	_ "github.com/yhonda-ohishi/db-handler-server/google/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_COMPLETED   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_COMPLETED",
		3: "PAYMENT_STATUS_FAILED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_COMPLETED":   2,
		"PAYMENT_STATUS_FAILED":      3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

// Transaction represents a toll transaction
type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CardId          string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	EntryGateId     string                 `protobuf:"bytes,3,opt,name=entry_gate_id,json=entryGateId,proto3" json:"entry_gate_id,omitempty"`
	ExitGateId      string                 `protobuf:"bytes,4,opt,name=exit_gate_id,json=exitGateId,proto3" json:"exit_gate_id,omitempty"`
	EntryTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=entry_time,json=entryTime,proto3" json:"entry_time,omitempty"`
	ExitTime        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=exit_time,json=exitTime,proto3" json:"exit_time,omitempty"`
	Distance        float64                `protobuf:"fixed64,7,opt,name=distance,proto3" json:"distance,omitempty"`
	TollAmount      int64                  `protobuf:"varint,8,opt,name=toll_amount,json=tollAmount,proto3" json:"toll_amount,omitempty"`
	DiscountAmount  int64                  `protobuf:"varint,9,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	FinalAmount     int64                  `protobuf:"varint,10,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	PaymentStatus   PaymentStatus          `protobuf:"varint,11,opt,name=payment_status,json=paymentStatus,proto3,enum=etc_meisai.v1.PaymentStatus" json:"payment_status,omitempty"`
	TransactionDate *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *Transaction) GetEntryGateId() string {
	if x != nil {
		return x.EntryGateId
	}
	return ""
}

func (x *Transaction) GetExitGateId() string {
	if x != nil {
		return x.ExitGateId
	}
	return ""
}

func (x *Transaction) GetEntryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EntryTime
	}
	return nil
}

func (x *Transaction) GetExitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExitTime
	}
	return nil
}

func (x *Transaction) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Transaction) GetTollAmount() int64 {
	if x != nil {
		return x.TollAmount
	}
	return 0
}

func (x *Transaction) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *Transaction) GetFinalAmount() int64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *Transaction) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Transaction) GetTransactionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionDate
	}
	return nil
}

// Request messages
type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTransactionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionHistoryRequest) Reset() {
	*x = GetTransactionHistoryRequest{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionHistoryRequest) ProtoMessage() {}

func (x *GetTransactionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionHistoryRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *GetTransactionHistoryRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetTransactionHistoryRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetTransactionHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTransactionHistoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type TransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionList) Reset() {
	*x = TransactionList{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionList) ProtoMessage() {}

func (x *TransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionList.ProtoReflect.Descriptor instead.
func (*TransactionList) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionList) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *TransactionList) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *TransactionList) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\retc_meisai.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x04\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12\"\n" +
	"\rentry_gate_id\x18\x03 \x01(\tR\ventryGateId\x12 \n" +
	"\fexit_gate_id\x18\x04 \x01(\tR\n" +
	"exitGateId\x129\n" +
	"\n" +
	"entry_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tentryTime\x127\n" +
	"\texit_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bexitTime\x12\x1a\n" +
	"\bdistance\x18\a \x01(\x01R\bdistance\x12\x1f\n" +
	"\vtoll_amount\x18\b \x01(\x03R\n" +
	"tollAmount\x12'\n" +
	"\x0fdiscount_amount\x18\t \x01(\x03R\x0ediscountAmount\x12!\n" +
	"\ffinal_amount\x18\n" +
	" \x01(\x03R\vfinalAmount\x12C\n" +
	"\x0epayment_status\x18\v \x01(\x0e2\x1c.etc_meisai.v1.PaymentStatusR\rpaymentStatus\x12E\n" +
	"\x10transaction_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionDate\"'\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe5\x01\n" +
	"\x1cGetTransactionHistoryRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x9c\x01\n" +
	"\x0fTransactionList\x12>\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1a.etc_meisai.v1.TransactionR\ftransactions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount*\x84\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x032\x90\x02\n" +
	"\x12TransactionService\x12u\n" +
	"\x0eGetTransaction\x12$.etc_meisai.v1.GetTransactionRequest\x1a\x1a.etc_meisai.v1.Transaction\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/transactions/{id}\x12\x82\x01\n" +
	"\x15GetTransactionHistory\x12+.etc_meisai.v1.GetTransactionHistoryRequest\x1a\x1e.etc_meisai.v1.TransactionList\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/transactionsB\xaf\x01\n" +
	"\x11com.etc_meisai.v1B\x10TransactionProtoP\x01Z7github.com/yhonda-ohishi/db-handler-server;etc_meisaiv1\xa2\x02\x03EXX\xaa\x02\fEtcMeisai.V1\xca\x02\fEtcMeisai\\V1\xe2\x02\x18EtcMeisai\\V1\\GPBMetadata\xea\x02\rEtcMeisai::V1b\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transaction_proto_goTypes = []any{
	(PaymentStatus)(0),                   // 0: etc_meisai.v1.PaymentStatus
	(*Transaction)(nil),                  // 1: etc_meisai.v1.Transaction
	(*GetTransactionRequest)(nil),        // 2: etc_meisai.v1.GetTransactionRequest
	(*GetTransactionHistoryRequest)(nil), // 3: etc_meisai.v1.GetTransactionHistoryRequest
	(*TransactionList)(nil),              // 4: etc_meisai.v1.TransactionList
	(*timestamppb.Timestamp)(nil),        // 5: google.protobuf.Timestamp
}
var file_transaction_proto_depIdxs = []int32{
	5, // 0: etc_meisai.v1.Transaction.entry_time:type_name -> google.protobuf.Timestamp
	5, // 1: etc_meisai.v1.Transaction.exit_time:type_name -> google.protobuf.Timestamp
	0, // 2: etc_meisai.v1.Transaction.payment_status:type_name -> etc_meisai.v1.PaymentStatus
	5, // 3: etc_meisai.v1.Transaction.transaction_date:type_name -> google.protobuf.Timestamp
	5, // 4: etc_meisai.v1.GetTransactionHistoryRequest.start_date:type_name -> google.protobuf.Timestamp
	5, // 5: etc_meisai.v1.GetTransactionHistoryRequest.end_date:type_name -> google.protobuf.Timestamp
	1, // 6: etc_meisai.v1.TransactionList.transactions:type_name -> etc_meisai.v1.Transaction
	2, // 7: etc_meisai.v1.TransactionService.GetTransaction:input_type -> etc_meisai.v1.GetTransactionRequest
	3, // 8: etc_meisai.v1.TransactionService.GetTransactionHistory:input_type -> etc_meisai.v1.GetTransactionHistoryRequest
	1, // 9: etc_meisai.v1.TransactionService.GetTransaction:output_type -> etc_meisai.v1.Transaction
	4, // 10: etc_meisai.v1.TransactionService.GetTransactionHistory:output_type -> etc_meisai.v1.TransactionList
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		EnumInfos:         file_transaction_proto_enumTypes,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
